name: Bayesian Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mavelli/rocker-bayesian

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies and run tests
      run: |
        Rscript -e "install.packages('remotes')"
        Rscript -e "remotes::install_deps()"
        Rscript -e "install.packages(c('devtools', 'testthat'))"
        Rscript -e "devtools::install('.')"  # Install local package
        Rscript -e "devtools::load_all()"
        Rscript -e "testthat::test_file('tests/testthat/test_bayesian_sa.R')"
