name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: [4.3.1]

    steps:
    - uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}

    - name: Install dependencies and run tests
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
      run: |
        Rscript -e "install.packages('remotes')"
        Rscript -e "remotes::install_deps()"
        Rscript -e "install.packages('testthat')"
        Rscript -e "remotes::install_local('.', dependencies = TRUE)"
        Rscript -e "testthat::test_dir('tests')"