name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rocker/r-ver:4.3.2

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies and run tests
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
      run: |
        Rscript -e "install.packages('remotes')"
        Rscript -e "remotes::install_deps()"
        Rscript -e "install.packages('testthat')"
        Rscript -e "remotes::install_local('.', dependencies = TRUE)"
        Rscript -e "testthat::test_dir('tests')"