name: Bayesian Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mavelli/rocker-bayesian

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      SKIP_BAYESIAN_SA_TESTS: false

    steps:
    - uses: actions/checkout@v4

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck
        needs: check

    - uses: r-lib/actions/check-r-package@v2
      with:
        upload-snapshots: true

    - uses: dorny/paths-filte@v3
      id: changes
      with:
        filters: |
          src:
            - "R/bayesian_causens.R"
            - "R/simData.R"
            - "tests/testthat/test_bayesian_sa.R"

    - name: Install dependencies and run tests
      if: steps.filter.outputs.src == "true"
      run: |
        Rscript -e "install.packages('remotes')"
        Rscript -e "remotes::install_deps()"
        Rscript -e "install.packages(c('devtools', 'testthat'))"
        Rscript -e "devtools::install('.')"  # Install local package
        Rscript -e "devtools::load_all()"
        Rscript -e "testthat::test_file('tests/testthat/test_bayesian_sa.R')"
